// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileReceiver>>
abstract class MobileReceiver implements RustOpaqueInterface {
  Future<Uint8List?> completedFile();

  static Future<MobileReceiver> default_() =>
      RustLib.instance.api.crateApiReceiverMobileReceiverDefault();

  /// Ingests one decoded QR payload and returns the latest UI snapshot.
  ///
  /// # Errors
  ///
  /// Returns a display-safe protocol error when the frame is invalid.
  Future<MobileSnapshot> ingest({required List<int> frame});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MobileReceiver> newInstance() =>
      RustLib.instance.api.crateApiReceiverMobileReceiverNew();

  Future<MobileSnapshot> snapshot();
}

enum MobileBlockKind { missing, partial, complete }

class MobileBlockState {
  final MobileBlockKind kind;
  final int unique;
  final int required_;

  const MobileBlockState({
    required this.kind,
    required this.unique,
    required this.required_,
  });

  @override
  int get hashCode => kind.hashCode ^ unique.hashCode ^ required_.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileBlockState &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          unique == other.unique &&
          required_ == other.required_;
}

enum MobilePhase { waitingManifest, receiving, complete }

class MobileSnapshot {
  final MobilePhase phase;
  final String? filename;
  final BigInt? totalBytes;
  final List<MobileBlockState> blocks;
  final BigInt? lastFrameIndex;

  const MobileSnapshot({
    required this.phase,
    this.filename,
    this.totalBytes,
    required this.blocks,
    this.lastFrameIndex,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      filename.hashCode ^
      totalBytes.hashCode ^
      blocks.hashCode ^
      lastFrameIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MobileSnapshot &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          filename == other.filename &&
          totalBytes == other.totalBytes &&
          blocks == other.blocks &&
          lastFrameIndex == other.lastFrameIndex;
}
