/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_webmanifestassembler_free: (a: number, b: number) => void;
export const __wbg_webreceiver_free: (a: number, b: number) => void;
export const __wbg_websender_free: (a: number, b: number) => void;
export const webmanifestassembler_new: () => number;
export const webmanifestassembler_push: (a: number, b: number, c: number) => [number, number, number];
export const webreceiver_acknowledge_segment: (a: number, b: number) => [number, number];
export const webreceiver_ingest: (a: number, b: number, c: number) => [number, number, number];
export const webreceiver_new: (a: number, b: number) => [number, number, number];
export const webreceiver_restore_completed_segment: (a: number, b: number) => [number, number];
export const webreceiver_snapshot_json: (a: number) => [number, number];
export const webreceiver_verify_persisted_segments: (a: number, b: any) => [number, number];
export const websender_manifest_frames: (a: number) => [number, number, number];
export const websender_new: (a: any) => [number, number, number];
export const websender_next_profile_frame: (a: number, b: number) => [number, number, number, number];
export const websender_preview_profile_frame: (a: number, b: number) => [number, number, number, number];
export const websender_seek_back: (a: number, b: number) => bigint;
export const websender_seek_forward: (a: number, b: number) => bigint;
export const websender_start_repair: (a: number, b: number) => [number, number];
export const websender_stop_repair: (a: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
