import { BrowserMultiFormatReader } from "@zxing/browser";
import init, { WebManifestAssembler, WebReceiver } from "../wasm/pkg/qrbeam_web";
import "../shared/style.css";

type ReceiverEvent = { kind: string; index?: number; bytes?: number[] };
const app = document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML = `<section class="panel"><p class="eyebrow">QRBEAM / RECEIVE</p><h1>接收文件</h1><button id="camera">打开相机</button><video class="camera" id="video" playsinline muted></video><p class="status" id="status">等待文件信息二维码</p><div class="progress"><i id="bar" style="width:0%"></i></div><div class="blocks" id="blocks"></div><button class="secondary" id="save" disabled>保存文件</button><details><summary>接收说明</summary><p>绿色：已安全写入本机存储。橙色：正在解码。接收完成后可保存原文件。</p></details></section>`;
const video = document.querySelector<HTMLVideoElement>("#video")!;
const status = document.querySelector<HTMLParagraphElement>("#status")!;
const blocks = document.querySelector<HTMLDivElement>("#blocks")!;
const bar = document.querySelector<HTMLElement>("#bar")!;
const save = document.querySelector<HTMLButtonElement>("#save")!;
let assembler: WebManifestAssembler, receiver: WebReceiver | undefined, manifest: Uint8Array | undefined, filename = "received.bin", originalLength = 0, segmentCount = 0, done = new Set<number>();
const db = await new Promise<IDBDatabase>((resolve, reject) => { const request = indexedDB.open("qrbeam-receiver", 1); request.onupgradeneeded = () => request.result.createObjectStore("segments"); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
const writeSegment = (index: number, bytes: Uint8Array) => new Promise<void>((resolve, reject) => { const tx = db.transaction("segments", "readwrite"); tx.objectStore("segments").put(bytes, index); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); });
const readSegment = (index: number) => new Promise<Uint8Array>((resolve, reject) => { const request = db.transaction("segments").objectStore("segments").get(index); request.onsuccess = () => resolve(new Uint8Array(request.result)); request.onerror = () => reject(request.error); });
function redraw() { const visible = Math.min(segmentCount, 200); blocks.innerHTML = Array.from({ length: visible }, (_, index) => `<i class="${done.has(index) ? "done" : ""}"></i>`).join(""); const percent = segmentCount ? (done.size / segmentCount) * 100 : 0; bar.style.width = `${percent}%`; status.textContent = segmentCount ? `${filename} · ${done.size}/${segmentCount} 区块 · ${Math.round(percent)}%` : "等待文件信息二维码"; if (done.size === segmentCount && segmentCount) { status.textContent = `接收完成：${filename}`; save.disabled = false; } }
function parseManifest(bytes: Uint8Array) { const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength); originalLength = Number(view.getBigUint64(28, true)); const filenameLength = view.getUint16(104, true); segmentCount = view.getUint32(108, true); filename = new TextDecoder().decode(bytes.slice(112, 112 + filenameLength)); }
async function ingest(bytes: Uint8Array) { if (!receiver) { const complete = assembler.push(bytes) as number[] | undefined; if (!complete) return; manifest = new Uint8Array(complete); parseManifest(manifest); receiver = new WebReceiver(manifest); redraw(); return; } const event = receiver.ingest(bytes) as ReceiverEvent; if (event.kind === "segment-ready" && event.index !== undefined && event.bytes) { const restored = new Uint8Array(event.bytes); await writeSegment(event.index, restored); receiver.acknowledge_segment(event.index); done.add(event.index); redraw(); } }
document.querySelector<HTMLButtonElement>("#camera")!.onclick = async () => { await init(); assembler = new WebManifestAssembler(); const reader = new BrowserMultiFormatReader(); await reader.decodeFromVideoDevice(undefined, video, result => { if (!result) return; const raw = (result as unknown as { getRawBytes(): Uint8Array }).getRawBytes(); void ingest(raw).catch(error => { status.textContent = `接收错误：${String(error)}`; }); }); status.textContent = "相机已开启，正在识别 QRBeam 帧"; };
save.onclick = async () => { const segments = await Promise.all(Array.from({ length: segmentCount }, (_, index) => readSegment(index))); const blob = new Blob(segments.map(segment => new Uint8Array(segment)), { type: "application/octet-stream" }); if (blob.size !== originalLength) { status.textContent = "文件长度校验失败，请继续补帧"; return; } const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); };
